project:
  type: website
  output-dir: _build
  pre-render: 
    - scripts/cleanup.py
    - scripts/generate.py
  resources:
  - index.json
  

website:
  title: "Extension Repo"
  navbar:
    left:
      - text: Home
        href: index.qmd
    tools:
      - icon: github
        href: https://github.com/BradyAJohnston/extensions

format:
  html:
    theme: 
      - darkly
      - assets/stylesheets/theme.scss
      - assets/stylesheets/extensions.scss
    css: styles.css
    toc: true