project:
  type: website
  output-dir: _build
  pre-render: 
    - generate.py
    - cleanup.py
  resources:
  - index.json
  

website:
  title: "Extension Repo"
  navbar:
    left:
      - text: Home
        href: index.qmd

format:
  html:
    theme: 
      - cosmo
      - assets/stylesheets/extensions.scss
    css: styles.css
    toc: true